name: Automate Data Preprocessing

on:
  push:
    paths:
      - 'breast_cancer_raw/**'
      - 'preprocessing/automate_*.py'
      - '.github/workflows/preprocessing.yml'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn
        
    - name: Run preprocessing script
      run: |
        cd Eksperimen_SML_Muhammad-Shirojul-Munir/preprocessing
        python automate_Muhammad-Shirojul-Munir.py
        
    - name: Commit and push processed data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Eksperimen_SML_Muhammad-Shirojul-Munir/breast_cancer_preprocessing/
        git commit -m "Auto-update processed data" || echo "No changes to commit"
        git push
